# Generated by Django 5.0.3 on 2024-03-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.CharField(max_length=100, verbose_name='Nations name')),
                ('country', models.CharField(max_length=200, verbose_name='Country name')),
                ('numb', models.IntegerField(verbose_name='Country number')),
                ('flag', models.ImageField(upload_to='media', verbose_name='Country flag')),
            ],
            options={
                'verbose_name': 'Nations list',
                'db_table': 'worldNation',
            },
        ),
    ]
